config/routes.rb
Rails.application.routes.draw do
  devise_for :members
  resources :posts, only: [:index, :new, :create]
  root 'posts#index'
  get '/about', to: 'static_pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :member
  validates :title, presence: true, uniqueness: true
  validates :body, presence: true, length: { maximum: 140 }
  scope :most_recent_first, -> { order(created_at: :desc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name])
    devise_parameter_sanitizer.permit(:account_update, keys:[:name])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_member!, only: [:new, :create]

  def index
    @posts = Post.most_recent_first
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.member_id = current_member.id
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://kit.fontawesome.com/b4937b662a.js', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700;900&display=swap" %>
  </head>

  <body>
    <%= render "shared/notifications" %>
    <%= render 'shared/header' %>

    <div class="container">
      <section class="section">
        <div class="columns">
          <div class="column"></div>
          <div class="column is-two-thirds">
            <%= yield %>
          </div>
          <div class="column"></div>
        </div>
      </section>
    </div>

  </body>
</html>

app/views/posts/_author.html.erb
<% if member_signed_in? %>
  <div class="content is-small">
  Written by fellow member <strong><%= post.member.name %></strong>.
  </div>
<% end %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="block">
    <div class="card">
      <header class="card-header"> 
          <p class="card-header-title is-centered title is-4"><%= post.title %></p>
      </header>

      <div class="card-content">
        <div class="content is-medium">
          <%= post.body %>
        </div>
        <div class="content is-small">
           Posted <%= time_ago_in_words(post.created_at)%> ago</p>
        </div>
        <%= render partial: 'author', locals: { post: post } %>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<h1 class="title">Create a post</h1>

<%= form_with model: @post do |form| %>
  <div class="field">
    <%= form.label :title, 'Post title', class: 'label' %>
    <div class="control">
      <%= form.text_field :title, class: 'input' %>
    </div>
  </div>

  <div class="field">
    <%= form.label :body, 'Post body', class: 'label' %>
    <div class="control">
      <%= form.text_area :body, placeholder: "Let your ideas flow...",
                         class: 'textarea' %>
    </div>
  </div>

  <div class="field">
    <%= form.submit class: 'button is-link' %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar is-light colored-navbar">
  <!-- Navbar brand -->
  <div class="navbar-brand">

    <div class="navbar-item content is-medium mb-0">
      <span class="icon-text">
        <span>MEMBERS ONLY&nbsp;</span>
        <span class="icon is-small">
          <i class="fas fa-mask"></i>&nbsp;
        </span>
      </span>
    </div>

    <div role="button" class="navbar-burger" data-target="navMenu"
         aria-label="menu" aria-expanded="false">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </div>

  </div>
  <!-- Navbar brand -->

  <!-- Navbar menu -->
  <div class="navbar-menu content is-medium" id="navMenu">

    <!-- Navbar start -->
    <div class="navbar-start">
      <%= link_to 'About', about_path, class: 'navbar-item' %>

      <%= link_to 'Posts', posts_path, class: 'navbar-item' %>

      <%= link_to 'New Post', new_post_path, class: 'navbar-item' %>
    </div>
    <!-- Navbar start -->

    <!-- Navbar end -->
    <div class="navbar-end">
      <%= render "shared/session_button_toggle" %>
    </div>
    <!-- Navbar end -->

  </div>
  <!-- Navbar menu -->

</nav>

app/views/shared/_notifications.html.erb
<% if flash[:notice] %>
  <div class="notification is-primary global-notification">
    <p class="notice"><%= notice %></p>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="notification is-danger global-notification">
    <p class="alert"><%= alert %></p>
  </div>
<% end %>

app/views/shared/_session_button_toggle.html.erb
<% if member_signed_in? %>

  <%= link_to destroy_member_session_path, method: :delete,
              class: 'navbar-item' do %>
    <p>Sign out <i class="fas fa-sign-in-alt"></i></p>
  <% end %>

<% else %>

  <%= link_to new_member_session_path, class: 'navbar-item' do%>
    <p>Sign in <i class="fas fa-sign-in-alt"></i></p>
  <% end %>

<% end %>

app/views/static_pages/about.html.erb
  <div class="block">
    <p>
    A place where members are able share posts whose writer is only to known
    to those belonging to the club. Everyone else will just have to guess the
    source. Feel free to express yourself in any way you'd like.
    </p>
  </div>